### ISSUE TITLE
Circular Dependencies Race Condition

### ISSUE THREAD

**Issue by NikkiDreams** [OrKoN/npm-link-shared#7]
Hi,
I gave this a whirl yesterday and ran into a fun race condition. 
Projects that are dependencies that have circular dependencies make for a really pretty messy situation. I have a main project with 8-10 local dependency projects to support it. (Not optimal and not my architecture, so I can't do much) Anyway, the joys of NPM Links showed it's darker side running this on my projects. Just wanted to point this out in the event one had an idea of a way to deal with deep circular dependency issues.

**$ npm-link-shared ./some_modules ./my_project**

```
./raptor-config has shared dependencies  [ './module-config-inc', './node-servicecore' ]
./module-config-inc has shared dependencies  [ './raptor-config' ]
./raptor-config has shared dependencies  [ './module-config-inc', './node-servicecore' ]
./module-config-inc has shared dependencies  [ './raptor-config' ]
util.js:429
    var simple = '\'' + JSON.stringify(value).replace(/^"|"$/g, '')
                                              ^

RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at formatPrimitive (util.js:429:47)
    at formatValue (util.js:227:19)
    at formatProperty (util.js:581:15)
    at formatArray (util.js:474:19)
    at formatValue (util.js:410:16)
    at inspect (util.js:109:10)
    at exports.format (util.js:48:20)
    at Console.log (console.js:39:34)
    at link (/usr/local/lib/node_modules/npm-link-shared/lib/link.js:139:15)
```

**Comment by SaltonSea374** [comment]
Thanks man its wrill

**Comment by SaltonSea374** [comment]
Whats up with that coz

**Comment by SaltonSea374** [comment]
Coz am blind to see the futhutistic stage

**Comment by SaltonSea374** [comment]
Thats prob

**Comment by SaltonSea374** [comment]
What other

**Comment by SaltonSea374** [comment]
> Hi,
> I gave this a whirl yesterday and ran into a fun race condition. 
> Projects that are dependencies that have circular dependencies make for a really pretty messy situation. I have a main project with 8-10 local dependency projects to support it. (Not optimal and not my architecture, so I can't do much) Anyway, the joys of NPM Links showed it's darker side running this on my projects. Just wanted to point this out in the event one had an idea of a way to deal with deep circular dependency issues.
> 
> **$ npm-link-shared ./some_modules ./my_project**
> 
> ```
> ./raptor-config has shared dependencies  [ './module-config-inc', './node-servicecore' ]
> ./module-config-inc has shared dependencies  [ './raptor-config' ]
> ./raptor-config has shared dependencies  [ './module-config-inc', './node-servicecore' ]
> ./module-config-inc has shared dependencies  [ './raptor-config' ]
> util.js:429
>     var simple = '\'' + JSON.stringify(value).replace(/^"|"$/g, '')
>                                               ^
> 
> RangeError: Maximum call stack size exceeded
>     at String.replace (native)
>     at formatPrimitive (util.js:429:47)
>     at formatValue (util.js:227:19)
>     at formatProperty (util.js:581:15)
>     at formatArray (util.js:474:19)
>     at formatValue (util.js:410:16)
>     at inspect (util.js:109:10)
>     at exports.format (util.js:48:20)
>     at Console.log (console.js:39:34)
>     at link (/usr/local/lib/node_modules/npm-link-shared/lib/link.js:139:15)
> ```
> 

Zzz
